apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ include "papermc.fullname" . }}
  labels:
    {{ include "papermc.labels" . | nindent 4 }}
spec:
  entryPoints:
    - {{ .Values.ingress.entrypoints.tcp | quote }}
  routes:
    - match: HostSNI(`*`)
      services:
        - name: {{ include "papermc.fullname" . }}
          port: {{ .Values.service.port }}
