apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "papermc.fullname" . }}
  labels:
    {{- include "papermc.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "papermc.selectorLabels" . | nindent 6 }}
  replicas: 1
  serviceName: {{ include "papermc.fullname" . }}-headless
  template:
    metadata:
      annotations:
        {{- include "papermc.configChecksumAnnotations" . | indent 8 }}
      labels:
        {{- include "papermc.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- range $i, $secretName := .Values.imagePullSecrets }}
        - name: {{ $secretName }}
        {{- end }}
      {{- end }}
      serviceAccountName: {{ include "papermc.serviceAccountName" . }}
      volumes:
        - name: paper-config
          configMap:
            name: {{ include "papermc.fullname" . }}
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsUser: 1000
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- if .Values.acceptEULA }}
            - name: ACCEPT_EULA
              value: 'y'
            {{- end }}
            {{- if .Values.overwriteSettings }}
            - name: OVERWRITE_SETTINGS
              value: 'y'
            {{- end }}
            - name: BASE_CONFIG_DIR
              value: /etc/papermc
            - name: SERVER_PORT
              value: {{ .Values.service.port | quote }}
            - name: ONLINE_MODE
              value: {{ .Values.onlineMode | quote }}
            - name: JAVA_OPTS
              value: >-
                -XX:+UnlockExperimentalVMOptions
                -XX:+UseContainerSupport
                -XX:MaxRAMPercentage=70
                {{- range $i, $opt := .Values.extraJAVAopts }}
                {{ $opt }}
                {{- end }}
          workingDir: /paper
          volumeMounts:
            - name: paper-config
              mountPath: /etc/papermc
            {{- if .Values.persistence.enabled }}
            - name: paper-data
              mountPath: /paper
              {{- if .Values.persistence.subPath }}
              subPath: {{ .Values.persistence.subPath }}
              {{- end }}
            {{- end }}
          ports:
            - name: minecraft
              containerPort: 25565
              protocol: TCP
          livenessProbe:
            exec:
              command:
                - /healthcheck
            initialDelaySeconds: {{ .Values.probesTimeout }}
          readinessProbe:
            exec:
              command:
                - /healthcheck
            initialDelaySeconds: {{ .Values.probesTimeout }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
  {{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: paper-data
    spec:
      accessModes:
      - {{ .Values.persistence.accessMode | quote }}
      {{- if .Values.persistence.storageClassName }}
      storageClassName: {{ .Values.persistence.storageClassName }}
      {{- end }}
      resources:
        requests:
          storage: {{ .Values.persistence.size }}
  {{- end }}