apiVersion: v1
kind: Secret
metadata:
  name: {{ include "benisbot.fullname" . }}-secrets
type: Opaque
data:
  botToken: {{ .Values.bot.token | b64enc }}
  jwtSecret: {{ .Values.api.jwtSecret | b64enc }}
  databaseUrl: {{ include "benisbot.postgresUrl" . | b64enc }}