apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "benisbot-frontend.fullname" . }}-config
data:
  # property-like keys; each key maps to a simple value
  backendUrl: {{ .Values.backend.url | quote }}
