{{- if .Values.ingress.enabled -}}
{{- $fullName := include "benisbot-frontend.fullname" . -}}
{{- $namespace := .Release.Namespace }}
{{- $svcPort := .Values.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "benisbot-frontend.fullname" . }}-https
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  tls:
    - secretName: {{ include "benisbot-frontend.fullname" . }}-tls
      hosts:
        - {{ .Values.ingress.host | quote }}
  rules:
  - host: {{ .Values.ingress.host | quote }}
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ include "benisbot-frontend.fullname" . }}
              port:
                number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "benisbot-frontend.fullname" . }}-http
  {{- with .Values.ingress.httpAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
    traefik.ingress.kubernetes.io/router.tls: "false"
    traefik.ingress.kubernetes.io/router.middlewares: {{ $namespace }}-{{ $fullName }}-http-redirect@kubernetescrd
  {{- end }}
spec:
  rules:
  - host: {{ .Values.ingress.host | quote }}
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ include "benisbot-frontend.fullname" . }}
              port:
                number: 80
---
# Redirect to https
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ include "benisbot-frontend.fullname" . }}-http-redirect
spec:
  redirectScheme:
    scheme: https
    permanent: true
{{- end }}
